# Jekyll Configuration
title: "Deep Dive into Agentic AI: Concepts, Design, and Real-World Applications"
description: "This learning material provides an in-depth exploration of Agentic AI, a rapidly evolving paradigm where artificial intelligence systems are designed to act autonomously, pursue goals, make decisions, and adapt to dynamic environments. The content goes beyond surface-level definitions to examine how agentic behaviors emerge from modern AI systems, especially those powered by large language models, planning algorithms, and tool-using capabilities.

Designed for intermediate-level learners, this content bridges theoretical foundations and practical implementation. Learners will gain a solid understanding of how agentic systems are structured, how they differ from reactive or purely model-based AI, and how they are being applied across industries. The material emphasizes design trade-offs, ethical considerations, and future directions to prepare learners for both development and critical evaluation of Agentic AI systems."
url: "https://m-rizqinovniari-25.github.io"
baseurl: "/agentic-handbook"

# Just the Docs Theme
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Markdown processor
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  parse_block_html: true

# Just the Docs Configuration
just_the_docs:
  search_enabled: true
  heading_anchors: true
  aux_links:
    
  
  color_scheme: "light"
  
# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
